### ISSUE TITLE
[No parser output]

### ISSUE THREAD

**Issue by james-hawley-pub** [Dustin42Codam/cub3d_destroyer#1]
Thank you for this amazing destroyer ! 
My program prints "Error\n" and details about the error. But when I launch the destroyer, it writes everywhere "no parser output". How can I make it works ? Thank you !
(tried to print it in fd = 0, 1 and 2, but doesnt seems to change anything)
<img width="340" alt="2" src="https://user-images.githubusercontent.com/72215294/97118883-dd03eb00-170c-11eb-9f25-bc8a0367180c.png">

**Comment by Dustin42Codam** [comment]
Hey James!
Can you please run your parser manually with one of the maps that don't seem to work properly and post the output?

**Comment by james-hawley-pub** [comment]
:)
<img width="404" alt="png" src="https://user-images.githubusercontent.com/72215294/97208833-dbddc700-17bb-11eb-9b5f-50a2f0173650.png">

**Comment by Dustin42Codam** [comment]
Weird. Printing to fd=1 should be fine. I will be doing some changes during the next week so make sure to git pull the repo regularly.

**Comment by james-hawley-pub** [comment]
this is now working since your last commits, thanks !
